apiVersion: v1
kind: Service
metadata:
  name: {{ include "ic-autopilot.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ic-autopilot.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ic-autopilot.backend.selectorLabels" . | nindent 4 }}
---
{{- if .Values.backend.internalLB.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ic-autopilot.fullname" . }}-backend-internal
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ic-autopilot.backend.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.backend.internalLB.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ic-autopilot.backend.selectorLabels" . | nindent 4 }}
{{- end }}
