{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ic-autopilot.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ic-autopilot.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ic-autopilot.backend.selectorLabels" . | nindent 6 }}
{{- end }}
