{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ic-autopilot.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ic-autopilot.labels" . | nindent 4 }}
  annotations:
    {{- include "ic-autopilot.workloadIdentity.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
